// elastic adaptive
export const SET_CURRENT_FONT_SIZE = 'SET_CURRENT_FONT_SIZE'
export const SET_USER_DEVICE_TYPE = 'SET_USER_DEVICE_TYPE'

// ui
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_MODAL_LOADING_STATE = 'TOGGLE_MODAL_LOADING_STATE'

// filtration
export const SET_PRIMARY_FILTER_VALUE = 'SET_PRIMARY_FILTER_VALUE'
export const SET_SECONDARY_FILTER_VALUE = 'SET_SECONDARY_FILTER_VALUE'
export const SET_FILTERED_DATA = 'SET_FILTERED_DATA'
export const SET_SECONDARY_FILTER_DATA = 'SET_SECONDARY_FILTER_DATA'
export const RESET_FILTERS = 'RESET_FILTERS'
export const SET_MANUAL_FILTER = 'SET_MANUAL_FILTER'
export const SET_DATE_FILTER_VALUE = 'SET_DATE_FILTER_VALUE'
