export const usersData = [
  {
    id: 1,
    name: `Гуменюк І. Б.`,
    email: `head@mail.com`,
    phone: `(097) 980 20 30`,
    role: `Начальник ЖК`,
    isEditButton: true,
    isDeleteButton: true,
  },
  {
    id: 2,
    name: `Гуменюк В. Б.`,
    email: `booker@mail.com`,
    phone: `(097) 980 20 30`,
    role: `Бухгалтер`,
    isEditButton: true,
    isDeleteButton: true,
  },
  {
    id: 3,
    name: `Грінченко Є. М.`,
    email: `operator1@mail.com`,
    phone: `(097) 980 20 30`,
    role: `Операціоніст`,
    isEditButton: true,
    isDeleteButton: true,
  },
  {
    id: 4,
    name: `Гаврилюк Л. Н.`,
    email: `operator2@mail.com`,
    phone: `(097) 980 20 30`,
    role: `Операціоніст`,
    isEditButton: true,
    isDeleteButton: true,
  },
  {
    id: 5,
    name: `Діденко Т.Г.`,
    email: `operator3@mail.com`,
    phone: `(097) 980 20 30`,
    role: `Операціоніст`,
    isEditButton: true,
    isDeleteButton: true,
  },
]
